[tool.poetry]
name = "rdf-prettifier"
version = "0.1.0"
description = "Prettifies RDF graphs"
authors = ["Digdir <fellesdatakatalog@digdir.no>"]
homepage = "https://github.com/Informasjonsforvaltning/rdf-prettifier"
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
fastapi = "^0.95.0"
uvicorn = {version = "^0.20.0"}
GitPython = "^3.1.27"
rdflib = "^6.2.0"
types-aiofiles = "^23.1.0"
aiofiles = "^22.1.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.971"
black = "^22.8.0"
flake8 = "^5.0.4"
flake8-annotations = "^2.9.1"
flake8-bandit = "^4.1.1"
flake8-black = "^0.3.3"
flake8-builtins = "^1.5.3"
flake8-bugbear = "^22.8.23"
flake8-docstrings = "^1.7.0"
flake8-import-order = "^0.18.1"
flake8-isort = "^4.2.0"
flake8-rst-docstrings = "^0.2.7"
pep8-naming = "^0.13.2"
pytest = "^7.1.3"
coverage = {extras = ["toml"], version = "^6.4.4"}
safety = "^2.1.1"
codecov = "^2.1.12"
pytest-docker = "^1.0.0"
requests = "^2.28.1"
types-requests = "^2.28.9"
PyYAML = "^6.0"
pytest-asyncio = "^0.19.0"


[tool.pytest.ini_options]
markers = [
  "unit: marks tests as unit (fast)",
  "integration: marks tests as integration (slower)",
  "contract: marks test as contract (slow)",
  "asyncio"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["rdf_prettifier"]

[tool.coverage.report]
fail_under = 100
