---
apiVersion: v1
kind: Service
metadata:
  name: rdf-prettifier
spec:
  selector:
    app: rdf-prettifier
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
