# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-09-07T11:14:00+00:00

from __future__ import annotations

from typing import Union

from fastapi import FastAPI
from fastapi.responses import PlainTextResponse

from .git import load_graph, store_graph
from .models import HTTPError, Graph, TemporalID
from .rdf import to_turtle

app = FastAPI(
    title="rdf-diff-store",
    description="Historical storage for rdf",
    version="0.1.0",
)


@app.get("/api/graphs", response_model=None, responses={"500": {"model": HTTPError}})
def get_api_graphs(body: TemporalID) -> Union[str, HTTPError]:
    """
    Get graph at specific time
    """
    try:
        return PlainTextResponse(load_graph(body.id))
    except Exception as e:
        return HTTPError(error=e)


@app.post("/api/graphs", response_model=None, responses={"500": {"model": HTTPError}})
def post_api_graphs(body: Graph) -> Union[None, HTTPError]:
    """
    Store graph
    """
    try:
        turtle = to_turtle(body.graph, body.format)
        store_graph(body.id, turtle)
    except Exception as e:
        return HTTPError(error=e)


@app.get("/livez")
def get_livez() -> str:
    return "ok"


@app.get("/readyz")
def get_readyz() -> str:
    return "ok"
