# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-09-07T11:14:00+00:00

from __future__ import annotations

from typing import Union

from fastapi import FastAPI

from .git import load_graph, store_graph
from .models import Error, Graph, TemporalID
from .rdf import to_turtle

app = FastAPI(
    title="rdf-diff-store",
    description="Historical storage for rdf",
    version="0.1.0",
)


@app.get("/api/graphs", response_model=str, responses={"500": {"model": Error}})
def get_api_graphs(body: TemporalID) -> Union[str, Error]:
    """
    Get graph at specific time
    """
    return load_graph(body.id)


@app.post("/api/graphs", response_model=None, responses={"500": {"model": Error}})
def post_api_graphs(body: Graph) -> Union[None, Error]:
    """
    Store graph
    """
    turtle = to_turtle(body.graph, body.format)
    store_graph(body.id, turtle)

    return None
