# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-09-07T12:21:13+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class HTTPError(BaseModel):
    message: Optional[str] = None
    error: Optional[str] = None


class TemporalID(BaseModel):
    id: str
    timestamp: Optional[int] = Field(None, description="Seconds since epoch")


class Graph(BaseModel):
    id: str
    format: Optional[str] = None
    graph: str
